// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"user-service/internal/data/ent/authprovider"
	"user-service/internal/data/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AuthProvider is the model entity for the AuthProvider schema.
type AuthProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType string `json:"provider_type,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID string `json:"provider_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AuthProviderQuery when eager-loading is set.
	Edges        AuthProviderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AuthProviderEdges holds the relations/edges for other nodes in the graph.
type AuthProviderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AuthProviderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authprovider.FieldID, authprovider.FieldUserID:
			values[i] = new(sql.NullInt64)
		case authprovider.FieldProviderType, authprovider.FieldProviderID:
			values[i] = new(sql.NullString)
		case authprovider.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthProvider fields.
func (_m *AuthProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case authprovider.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case authprovider.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = value.String
			}
		case authprovider.FieldProviderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.String
			}
		case authprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthProvider.
// This includes values selected through modifiers, order, etc.
func (_m *AuthProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the AuthProvider entity.
func (_m *AuthProvider) QueryUser() *UserQuery {
	return NewAuthProviderClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this AuthProvider.
// Note that you need to call AuthProvider.Unwrap() before calling this method if this AuthProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthProvider) Update() *AuthProviderUpdateOne {
	return NewAuthProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthProvider) Unwrap() *AuthProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthProvider) String() string {
	var builder strings.Builder
	builder.WriteString("AuthProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(_m.ProviderType)
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(_m.ProviderID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuthProviders is a parsable slice of AuthProvider.
type AuthProviders []*AuthProvider
