// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"user-service/internal/data/ent/authprovider"
	"user-service/internal/data/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthProviderCreate is the builder for creating a AuthProvider entity.
type AuthProviderCreate struct {
	config
	mutation *AuthProviderMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AuthProviderCreate) SetUserID(v int64) *AuthProviderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProviderType sets the "provider_type" field.
func (_c *AuthProviderCreate) SetProviderType(v string) *AuthProviderCreate {
	_c.mutation.SetProviderType(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *AuthProviderCreate) SetProviderID(v string) *AuthProviderCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthProviderCreate) SetCreatedAt(v time.Time) *AuthProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthProviderCreate) SetNillableCreatedAt(v *time.Time) *AuthProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthProviderCreate) SetID(v int64) *AuthProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AuthProviderCreate) SetUser(v *User) *AuthProviderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AuthProviderMutation object of the builder.
func (_c *AuthProviderCreate) Mutation() *AuthProviderMutation {
	return _c.mutation
}

// Save creates the AuthProvider in the database.
func (_c *AuthProviderCreate) Save(ctx context.Context) (*AuthProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthProviderCreate) SaveX(ctx context.Context) *AuthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthProviderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthProviderCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthProvider.user_id"`)}
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		return &ValidationError{Name: "provider_type", err: errors.New(`ent: missing required field "AuthProvider.provider_type"`)}
	}
	if v, ok := _c.mutation.ProviderType(); ok {
		if err := authprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "AuthProvider.provider_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "AuthProvider.provider_id"`)}
	}
	if v, ok := _c.mutation.ProviderID(); ok {
		if err := authprovider.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "AuthProvider.provider_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthProvider.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AuthProvider.user"`)}
	}
	return nil
}

func (_c *AuthProviderCreate) sqlSave(ctx context.Context) (*AuthProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthProviderCreate) createSpec() (*AuthProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authprovider.Table, sqlgraph.NewFieldSpec(authprovider.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProviderType(); ok {
		_spec.SetField(authprovider.FieldProviderType, field.TypeString, value)
		_node.ProviderType = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(authprovider.FieldProviderID, field.TypeString, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   authprovider.UserTable,
			Columns: []string{authprovider.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AuthProviderCreateBulk is the builder for creating many AuthProvider entities in bulk.
type AuthProviderCreateBulk struct {
	config
	err      error
	builders []*AuthProviderCreate
}

// Save creates the AuthProvider entities in the database.
func (_c *AuthProviderCreateBulk) Save(ctx context.Context) ([]*AuthProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthProviderCreateBulk) SaveX(ctx context.Context) []*AuthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
