// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthProvider is the predicate function for authprovider builders.
type AuthProvider func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
