// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user-service/internal/biz"
	"user-service/internal/conf"
	"user-service/internal/data"
	"user-service/internal/server"
	"user-service/internal/service"
	"user-service/third_party/snowflake"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, node *snowflake.Node, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	userRepo := data.NewUserRepo(dataData, logger, node)
	authProviderRepo := data.NewAuthProviderRepo(dataData, logger)
	userAuthCase := biz.NewUserAuthCase(userRepo, authProviderRepo, logger)
	userCase := biz.NewUserCase(userRepo, logger)
	loginService := service.NewLoginService(jwt, logger, node, userAuthCase, userCase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, loginService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, loginService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
